// app/layout.jsx
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "./Component/Nav";
import Footer from "./Component/Footer";
import AuthProvider from "./Context/AuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased container mx-auto`}
      >
        <AuthProvider>
          <div className="flex flex-col min-h-screen">
            <header>
              <Nav />
            </header>

            <main className="flex-1">{children}</main>

            <Footer />
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
